# Generated by Django 3.1.2 on 2020-10-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraper',
            old_name='search',
            new_name='source',
        ),
    ]
